### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alexandre-sullet-cko** [nteract/data-explorer#29]
Hello,

You're saying to go to the application folder here : 

```
cd applications/jupyter-extension
pip install -e .
jupyter serverextension enable nteract_on_jupyter
```

but where is this folder ? 

If this is the Applications folder from root, I don't have anything in it.

Thanks for your help :)

**Comment by rgbkrk** [comment]
Those are the old instructions from back when this package was part of the nteract/nteract repo. I'm not sure what the right way to hack on this now is. cc @emeeks @captainsafia

**Comment by captainsafia** [comment]
We've got styleguidist set up on the repo for local dev now. You can check out the README in the `master` branch for the latest instructions.

**Comment by willingc** [comment]
[Installation instructions for local developement](https://github.com/nteract/data-explorer/blob/master/README.md#hacking-on-the-nteract-data-explorer)

I'm also going to move the monorepo installation instructions to `LEGACY.md`.

Closing this issue.
