### ISSUE TITLE
Data-explorer WITHIN jupyterlab, not jupyter nteract

### ISSUE THREAD

**Issue by Nestak2** [nteract/data-explorer#9]
I really like the data-explorer and would like to install it to work WITHIN jupyterlab, not jupyter nteract. Apparently, this is possible, as I see in this [post](https://code.tubitv.com/building-a-model-driven-enterprise-3f37efa9db94), or just see image below:
![BgSjI](https://user-images.githubusercontent.com/16193553/73346040-d6376d00-428d-11ea-8090-d59ab369f39d.png)
But I find no installation instructions for integration into jupyterlab. Can you provide some? It seems that other people are interested in [this functionality](https://stackoverflow.com/questions/59516688/jupyterlab-install-nteracts-data-explorer-as-an-extention#comment106033425_59516688), too. Thanks

**Comment by BenRussert** [comment]
The data explorer compiles to javascript and is built for the web. You can use it in any number of places, but it is only a component so you would have to figure out how to integrate it if you have a particular platform in mind. 

If you are interested in building something for jupyterlab I'd start with their [docs page](https://jupyterlab.readthedocs.io/)

**Comment by Nestak2** [comment]
@BenRussert Thanks for the info, I found a way to ingerate the data-explorer in jupyterlab and made a [post](https://stackoverflow.com/a/60028884/5838180) in stackoverlow explaining how

**Comment by springuper** [comment]
@Nestak2 we just open source our data explorer extension: https://code.tubitv.com/introducing-tubi-data-runtime-387e8651d08a, https://github.com/Tubitv/jupyterlab-extensions

**Comment by Nestak2** [comment]
@springuper Thanks, it looks interesting! I tried it out, but unfortunately it doesn't install properly for me, see [here](https://github.com/Tubitv/jupyterlab-extensions/issues/4#issue-600966952)
